### ISSUE TITLE
MVP Review

### ISSUE THREAD

**Issue by danemauland** [thedaebu/reallysmart#1]
Hey Eddie, phenomenal job on your MVPs! They are really thought out and you paid great attention to the details. Some minor revisions:

-Fill in the projected completion dates
New Account Creation
-Make the log out part of the MVP itself instead of a bonus. You're going to want this functionality anyways when testing your code
Comments
-Remove the "(Maybe)" from the third bullet point, this is the major purpose of using React/Redux, you'll be able to figure this out

**Comment by thedaebu** [comment]
I have filled in the dates. I made the log out step not be a bonus.
