### ISSUE TITLE
Comments MVP Review

### ISSUE THREAD

**Issue by thedaebu** [thedaebu/reallysmart#11]
Hey Dane, I am ready for my comments MVP review.

**Comment by thedaebu** [comment]
test

**Comment by danemauland** [comment]
Add in the time since the comment was posted. Other than that, nice work!

**Comment by thedaebu** [comment]
I have added in a time for each comment. 
On a side note, my computer is again seeding a previous version of my seeds so there are only tracks that are seeded as of this moment.
