### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by danemauland** [thedaebu/reallysmart#2]
Your MVPs are very CRUD-heavy so your schema is going to be a bit more involved that other projects. With that being said, you did a great job with the basic database design. I only have a couple improvements:

-Use polymorphic associations for comments on annotations/tracks and for upvotes. Look these up in the rails docs.
-List the associations for each table below the respective table
Upvotes
-What constraints do you need to add to prevent a user from upvoting something multiple times?

**Comment by thedaebu** [comment]
I edited the tables for comments and upvotes to allow for polymorphic associations with tracks and annotations. I have also added a constraint to allow a user to have only one upvote per track or annotation.
