### ISSUE TITLE
Sample State Review

### ISSUE THREAD

**Issue by danemauland** [thedaebu/reallysmart#4]
Nice work on your sample state! Some things to consider:

Upvotes
-Consider the minimum amount of information you really need here. What's the purpose of having the upvotes in the state? Can you accomplish the same thing without having to send all the details on every single upvote to your frontend? You can imagine that this would start taking up a lot of space once you get comments/annotations with large numbers of upvotes
-If an upvote is for a comment, you will likely still want an annotation_id key but set to null. This can help prevent bugs in your code later.
Errors
-Check for typos in your commentForm slice

**Comment by thedaebu** [comment]
I am still working on figuring out how to do this upvote issue but I did make a few edits.

**Comment by thedaebu** [comment]
Changed up the sample state for the tracks/annotation/comments/upvotes. I changed the tracks to include their own annotations and comments. I changed the annotations to include their own comments. I changed the upvotes where upvotes can be applied to each annotation or track.
