### ISSUE TITLE
Frontend Routes Review

### ISSUE THREAD

**Issue by danemauland** [thedaebu/reallysmart#5]
Good job on your frontend routes! Only a couple comments:

/
-Is this only going to show one TrackIndexItem? That's what this currently implies. Maybe list the component here as "TrackIndex" with "TrackIndexItem" nested below it

-Looks like you have a blank bullet point here, please remove that while making the above edit

**Comment by thedaebu** [comment]
I had edited to have a more proper file flow but still working on the upvote function.

**Comment by thedaebu** [comment]
I was able to reorganize my routes structure. I changed the home page to have only the track index. I changed the individual track pages to have the track item. Each track item would have its own annotation and comment items. Each annotation item would have its own comment items.
